Feat/adding components
Mahmoud-AbdElaziz-Hamed/messenger-webapp pull request #1
Opened 2024-01-22 21:33 UTC by Mahmoud-AbdElaziz-Hamed

create components

2024-01-25 10:16 UTC, yasserhennawi reviewed
- add constant width 250px to the "Side bar / User list", the remaining chatbox should be flexable 
- add `const CURRENT_USER_ID = 1;` in the ChatPage and use instead of login logic
- Add activeUserId state

2024-01-25 10:16 UTC, yasserhennawi commented on src/components/Avatar/index.jsx
> +// eslint-disable-next-line react/prop-types
Let's remove this.

2024-01-25 10:16 UTC, yasserhennawi commented on src/components/Avatar/index.jsx
> +  return <img src={src} alt="user avatar" className={className} />;
let's pass property `width`

2024-01-25 10:16 UTC, yasserhennawi commented on src/components/UserItem/index.jsx
> +export const UserItem = ({ userName, AVATAR_SRC, isOnline }) => {
this should be camelCase

2024-01-25 10:16 UTC, yasserhennawi commented on src/components/ChatBox/index.jsx
> +  const fristUserId = 3;
first*

2024-01-25 10:16 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +    setSearchValue(e.target.value);
1- if condition is not needed
2- we should not setSearchValue inside the clickHandler

2024-01-25 10:16 UTC, yasserhennawi commented on src/main.jsx
Investiage why single quotes changed to double, and adjust the settings to be always single quotes.

2024-02-08 08:10 UTC, Mahmoud-AbdElaziz-Hamed commented on src/components/Avatar/index.jsx
> +  return <img src={src} alt="user avatar" className={className} />;
done

2024-02-08 08:11 UTC, Mahmoud-AbdElaziz-Hamed commented on src/components/UserItem/index.jsx
> +export const UserItem = ({ userName, AVATAR_SRC, isOnline }) => {
done

2024-02-08 08:12 UTC, Mahmoud-AbdElaziz-Hamed commented on src/components/ChatBox/index.jsx
> +  const fristUserId = 3;
done

2024-02-08 08:13 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/ChatPage/index.jsx
> +    setSearchValue(e.target.value);
done

2024-02-08 08:13 UTC, Mahmoud-AbdElaziz-Hamed commented on src/main.jsx
done

2024-02-23 06:00 UTC, yasserhennawi requested changes

2024-02-23 06:00 UTC, yasserhennawi commented on src/components/ChatBox/index.jsx
> +  const filteredMessages = messages;
this line is not needed right? we can use `messages` directly

2024-02-23 06:00 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +            : 'w-72 hidden md:inline-block lg:inline-block xl:inline-block 2xl:inline-block'
this container will need `flex-shrink: 0` because on desktop, if you change the screen size, this container shrinks

2024-02-23 06:00 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +        }
this other API is not really needed. your new message is already added to the DB, and you know it's sender (which is you) and the body (messageValue)

So instead of calling another API, this function can be named `sendMessage` only, and after the POST api succeed, you can manually insert a new message in the `messages` state (using Date.now(), messageValue and currentUserId) and it should appear on the screen ;)

2024-02-23 06:00 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +        const response = await getAllMessages(receiverId).catch((error) => {
`.catch` is using the old promises approach, now that we use try/catch for cleaner code, you can expect that any error happens here will be sent to the `catch` part of the try/catch. 

So let's remove all the `.catch` after the APIs, and move the logic to the bottom catch

2024-02-23 06:00 UTC, yasserhennawi commented on src/containers/LoginPage/index.jsx
> +      if (response.status === 200) {
normally if any "failing" statusCode happens, the fetch functions throws an error, then it will exit the `try` to go to the `catch` so the if condition is not really needed right?

2024-02-23 06:00 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +  };
is this function needed it all?, we search when a letter is being typed. 
Does something happen if we don't set the value on Click?

2024-02-24 07:59 UTC, Mahmoud-AbdElaziz-Hamed commented on src/components/ChatBox/index.jsx
> +  const filteredMessages = messages;
right, done

2024-02-24 08:02 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/ChatPage/index.jsx
> +            : 'w-72 hidden md:inline-block lg:inline-block xl:inline-block 2xl:inline-block'
done

2024-02-24 08:47 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/ChatPage/index.jsx
> +        }
done

2024-02-24 09:02 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/ChatPage/index.jsx
> +        const response = await getAllMessages(receiverId).catch((error) => {
it doesn't give me the same effect

2024-02-24 09:04 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/LoginPage/index.jsx
> +      if (response.status === 200) {
right, done

2024-02-24 09:05 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/ChatPage/index.jsx
> +  };
that's right, done

2024-02-25 18:52 UTC, yasserhennawi commented on src/containers/ChatPage/index.jsx
> +        const response = await getAllMessages(receiverId).catch((error) => {
Solved ✅

2024-02-25 18:53 UTC, yasserhennawi commented on src/containers/LoginPage/index.jsx
> +      if (response.status === 200) {
Please check other places

2024-02-26 12:59 UTC, Mahmoud-AbdElaziz-Hamed commented on src/containers/LoginPage/index.jsx
> +      if (response.status === 200) {
done

2024-02-27 20:49 UTC, yasserhennawi commented
Great! 🚀 🎉

2024-02-27 20:49 UTC, merged